### ISSUE TITLE
"demo" is empty

### ISSUE THREAD

**Issue by yeyingdege** [intelligent-control-lab/Intent_Traj_Prediction#1]
Hi, nice work. I can find your dataset that's saved in pickle file, but the demo file is empty.

**Comment by yeyingdege** [comment]
It also seems that the pickle file cannot be loaded.

**Comment by Walleclipse** [comment]
Hi,
1. You need to load the pkl data with python `joblib` library:
```
import joblib
data_path='./human_kinect.pkl'
data=joblib.load(data_path)
train_data=data['train']
valid_data=data['valid']
test_data=data['test']
print(train_data.keys())
```

2.  About the demo, please check our recent [paper](https://arxiv.org/pdf/1912.01790.pdf)  and [video](https://www.youtube.com/watch?v=15vXtd5rg70&feature=youtu.be).
